version: "3.8"
services:
  alive-target:
    deploy:
      replicas: 3
    build:
      context: .
      target: connect-target
      additional_contexts:
        - php:nginx=docker-image://ghcr.io/benzine-framework/php:nginx-8.2
    image: ghcr.io/benzine-framework/swarm-connectivity-tester:target

  reporter:
    build:
      context: .
      target: connect-reporter
      additional_contexts:
        - php:nginx=docker-image://ghcr.io/benzine-framework/php:nginx-8.2
    image: ghcr.io/benzine-framework/swarm-connectivity-tester:reporter
    ports:
      - "127.0.0.6:8080:80"
    environment:
      TARGETS: "alive-target,dead-target"
      DEBUG: "true"
    volumes:
      - ./:/app
      - ./public-reporter:/app/public
