name: Build Swarm Connectivity Tester

permissions:
  contents: read
  packages: write

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 14 * * 2" # 2pm Patch Tuesday

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  swarm-connectivity-tester-build:
    name: Build Swarm Connectivity Tester
    runs-on: ubuntu-latest
    steps:
      - uses: benzine-framework/action-setup-php@main
      - uses: benzine-framework/action-get-datetime@main
      - uses: benzine-framework/action-setup-docker@main
        with:
          ghcr_user: matthewbaggett
          ghcr_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build: Build & Push Target Image"
        uses: docker/build-push-action@v5
        with:
          context: .
          target: connect-target
          platforms: ${{ github.actor != 'nektos/act' && env.PLATFORMS || 'linux/amd64' }}
          pull: true
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            benzine/swarm-connectivity-tester:target
            ghcr.io/benzine-framework/swarm-connectivity-tester:target
          cache-from: ${{ env.DOCKER_CACHE_FROM }}
          cache-to: ${{ env.DOCKER_CACHE_TO }}
          build-contexts: |
            php:cli=docker-image://ghcr.io/benzine-framework/php:cli-8.2
            php:nginx=docker-image://ghcr.io/benzine-framework/php:nginx-8.2

      - name: "Build: Build & Push Report Image"
        uses: docker/build-push-action@v5
        with:
          context: .
          target: connect-reporter
          platforms: ${{ github.actor != 'nektos/act' && env.PLATFORMS || 'linux/amd64' }}
          pull: true
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            benzine/swarm-connectivity-tester:reporter
            ghcr.io/benzine-framework/swarm-connectivity-tester:reporter
          cache-from: ${{ env.DOCKER_CACHE_FROM }}
          cache-to: ${{ env.DOCKER_CACHE_TO }}
          build-contexts: |
            php:cli=docker-image://ghcr.io/benzine-framework/php:cli-8.2
            php:nginx=docker-image://ghcr.io/benzine-framework/php:nginx-8.2
